version: "3"

services:
    server:
        image: alefly/server:v2
        container_name: server
        ports:
          - "1500:8080"
        depends_on:
          - redis
          - mongo
        networks:
          - server_net
        build:
            context: .
            dockerfile: Dockerfile
    redis:
        image: redis:latest
        container_name: redis
        ports:
          - "6379:6379"
        networks:
          - server_net
    mongo:
        image: mongo:latest
        container_name: mongo
        ports:
          - "27017:27017"
        networks:
          - server_net
networks:
    server_net:
